on: [push]
jobs:
  build_and_static_analysis:
    runs-on: ubuntu-latest
    container:
        image: kenadis/msp430-gcc-9.3.1.11:latest
    steps:
        - name: Checkout the repository
          uses: actions/checkout@v3
        - name: Build project
          run: make
        - name: Run static analysis
          run: make cppcheck