on: [push]
jobs:
  build_and_static_analysis:
    runs-on: ubuntu-latest
    container:
        image: kenadis/msp430-gcc-9.3.1.11:latest
    steps:
        - name: Checkout the repository
          uses: actions/checkout@v3
        - name: Set tools path
          run: echo "TOOLS_PATH=/home/ubuntu/dev/tools" >> $GITHUB_ENV
        - name: Build project
          run: make
        - name: Run static analysis
          run: make cppcheck